// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MuseumSystem.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MuseumSystem.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MuseumDbContext))]
    [Migration("20260824000200_AddPhotographyRequestSchema")]
    partial class AddPhotographyRequestSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("museum")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", "museum");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "museum");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "museum");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", "museum");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "museum");
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.ArtifactRegistry.Artifact", b =>
                {
                    b.Property<Guid>("ArtifactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BasicDescription")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<Guid?>("CreatedFromImportBatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentHolderName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("CurrentHolderType")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("CurrentLocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("ItemNumber")
                        .HasColumnType("integer");

                    b.Property<Guid?>("LastKnownStorageLocationId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("MuseumNumberDisplay")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.HasKey("ArtifactId");

                    b.HasIndex("CurrentLocationId");

                    b.HasIndex("LastKnownStorageLocationId");

                    b.HasIndex("CategoryId", "ItemNumber")
                        .IsUnique();

                    b.ToTable("Artifacts", "museum");
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.ArtifactRegistry.ArtifactCategory", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("NameArabic")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("CategoryId");

                    b.HasIndex("CategoryCode")
                        .IsUnique();

                    b.ToTable("ArtifactCategories", "museum");
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.Documentation.DocumentationRecord", b =>
                {
                    b.Property<Guid>("DocumentationRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CompletedBaselineValuesJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("CompletedBaselineValues");

                    b.Property<string>("CompletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("DocumentationTemplateVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ValuesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("Values");

                    b.HasKey("DocumentationRecordId");

                    b.HasIndex("ArtifactId")
                        .IsUnique();

                    b.HasIndex("DocumentationTemplateVersionId");

                    b.ToTable("DocumentationRecords", "museum");
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.Documentation.DocumentationRevision", b =>
                {
                    b.Property<Guid>("DocumentationRevisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeSummaryJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("ChangeSummary");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("DocumentationRecordId")
                        .HasColumnType("uuid");

                    b.Property<string>("NewValuesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("NewValues");

                    b.Property<string>("PreviousValuesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("PreviousValues");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("TemplateVersionId")
                        .HasColumnType("uuid");

                    b.HasKey("DocumentationRevisionId");

                    b.HasIndex("TemplateVersionId");

                    b.HasIndex("DocumentationRecordId", "RevisionNumber")
                        .IsUnique();

                    b.ToTable("DocumentationRevisions", "museum");
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.Documentation.DocumentationTemplate", b =>
                {
                    b.Property<Guid>("DocumentationTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtifactCategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("DocumentationTemplateId");

                    b.HasIndex("ArtifactCategoryId")
                        .IsUnique();

                    b.ToTable("DocumentationTemplates", "museum");
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.Documentation.DocumentationTemplateField", b =>
                {
                    b.Property<Guid>("DocumentationTemplateFieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("DocumentationTemplateVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("FieldKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("FieldType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("HelpText")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("DocumentationTemplateFieldId");

                    b.HasIndex("DocumentationTemplateVersionId", "FieldKey")
                        .IsUnique();

                    b.ToTable("DocumentationTemplateFields", "museum");
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.Documentation.DocumentationTemplateFieldOption", b =>
                {
                    b.Property<Guid>("DocumentationTemplateFieldOptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("DocumentationTemplateFieldId")
                        .HasColumnType("uuid");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("OptionKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("DocumentationTemplateFieldOptionId");

                    b.HasIndex("DocumentationTemplateFieldId", "OptionKey")
                        .IsUnique();

                    b.ToTable("DocumentationTemplateFieldOptions", "museum");
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.Documentation.DocumentationTemplateVersion", b =>
                {
                    b.Property<Guid>("DocumentationTemplateVersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ActivatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("DocumentationTemplateId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RetiredBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("DocumentationTemplateVersionId");

                    b.HasIndex("DocumentationTemplateId")
                        .IsUnique()
                        .HasDatabaseName("IX_DocumentationTemplateVersions_OneActivePerTemplate")
                        .HasFilter("\"Status\" = 'Active'");

                    b.HasIndex("DocumentationTemplateId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("DocumentationTemplateVersions", "museum");
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.IdentityAccess.AuditEntry", b =>
                {
                    b.Property<Guid>("AuditEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ActorUserId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ChangeSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("AuditEntryId");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("ModuleName", "EntityName", "EntityId");

                    b.ToTable("AuditEntries", "museum");
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.Import.ImportBatch", b =>
                {
                    b.Property<Guid>("ImportBatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AcceptedRows")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CommittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CommittedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("RejectedRows")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("TotalRows")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UploadedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("ValidatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ValidatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("ImportBatchId");

                    b.ToTable("ImportBatches", "museum");
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.Import.ImportRow", b =>
                {
                    b.Property<Guid>("ImportRowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryValue")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("DescriptionValue")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("ImportBatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("Issues")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ItemNumberValue")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LocationValue")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ProposedArtifactId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProposedCategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProposedLocationId")
                        .HasColumnType("uuid");

                    b.Property<int>("RowNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("ImportRowId");

                    b.HasIndex("ImportBatchId");

                    b.ToTable("ImportRows", "museum");
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.Photography.ArtifactImage", b =>
                {
                    b.Property<Guid>("ArtifactImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uuid");

                    b.Property<string>("Caption")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedByUserId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("DeletionMode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DeletionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("OriginalFilename")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("OriginalObjectKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("PhotographySetId")
                        .HasColumnType("uuid");

                    b.Property<int>("PixelHeight")
                        .HasColumnType("integer");

                    b.Property<int>("PixelWidth")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UploadedByUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("ArtifactImageId");

                    b.HasIndex("ArtifactId");

                    b.HasIndex("OriginalObjectKey")
                        .IsUnique();

                    b.HasIndex("PhotographySetId", "ArtifactId");

                    b.ToTable("ArtifactImages", "museum", t =>
                        {
                            t.HasCheckConstraint("CK_ArtifactImages_DeletionMode", "\"DeletionMode\" IS NULL OR \"DeletionMode\" IN ('UploaderGracePeriod', 'Privileged')");

                            t.HasCheckConstraint("CK_ArtifactImages_FileSizeBytes", "\"FileSizeBytes\" > 0");

                            t.HasCheckConstraint("CK_ArtifactImages_PixelHeight", "\"PixelHeight\" > 0");

                            t.HasCheckConstraint("CK_ArtifactImages_PixelWidth", "\"PixelWidth\" > 0");

                            t.HasCheckConstraint("CK_ArtifactImages_Status", "\"Status\" IN ('Available', 'DeletePending', 'Deleted')");
                        });
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.Photography.ArtifactImageDerivative", b =>
                {
                    b.Property<Guid>("ArtifactImageDerivativeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtifactImageId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("PixelHeight")
                        .HasColumnType("integer");

                    b.Property<int>("PixelWidth")
                        .HasColumnType("integer");

                    b.HasKey("ArtifactImageDerivativeId");

                    b.HasIndex("ArtifactImageId");

                    b.HasIndex("ObjectKey")
                        .IsUnique();

                    b.ToTable("ArtifactImageDerivatives", "museum", t =>
                        {
                            t.HasCheckConstraint("CK_ArtifactImageDerivatives_FileSizeBytes", "\"FileSizeBytes\" > 0");

                            t.HasCheckConstraint("CK_ArtifactImageDerivatives_Kind", "\"Kind\" IN ('Thumbnail', 'Preview')");

                            t.HasCheckConstraint("CK_ArtifactImageDerivatives_PixelHeight", "\"PixelHeight\" > 0");

                            t.HasCheckConstraint("CK_ArtifactImageDerivatives_PixelWidth", "\"PixelWidth\" > 0");
                        });
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.Photography.ArtifactPhotographyState", b =>
                {
                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uuid");

                    b.Property<int>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<Guid?>("PrimaryImageId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("ArtifactId");

                    b.HasIndex("PrimaryImageId");

                    b.HasIndex("PrimaryImageId", "ArtifactId");

                    b.ToTable("ArtifactPhotographyStates", "museum");
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.Photography.PhotographyRequest", b =>
                {
                    b.Property<Guid>("PhotographyRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CancelledByUserId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CompletedByUserId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<Guid?>("FulfillingPhotographySetId")
                        .HasColumnType("uuid");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestedByUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("PhotographyRequestId");

                    b.HasIndex("ArtifactId");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("ArtifactId", "Status");

                    b.HasIndex("FulfillingPhotographySetId", "ArtifactId", "Purpose");

                    b.ToTable("PhotographyRequests", "museum", t =>
                        {
                            t.HasCheckConstraint("CK_PhotographyRequests_CancelledMetadata", "(\"Status\" = 'Cancelled' AND \"CancelledByUserId\" IS NOT NULL AND \"CancelledAt\" IS NOT NULL AND \"FulfillingPhotographySetId\" IS NULL AND \"CompletedByUserId\" IS NULL AND \"CompletedAt\" IS NULL)\r\nOR (\"Status\" <> 'Cancelled' AND \"CancelledByUserId\" IS NULL AND \"CancelledAt\" IS NULL)");

                            t.HasCheckConstraint("CK_PhotographyRequests_CompletedMetadata", "(\"Status\" = 'Completed' AND \"FulfillingPhotographySetId\" IS NOT NULL AND \"CompletedByUserId\" IS NOT NULL AND \"CompletedAt\" IS NOT NULL AND \"CancelledByUserId\" IS NULL AND \"CancelledAt\" IS NULL)\r\nOR (\"Status\" <> 'Completed' AND \"FulfillingPhotographySetId\" IS NULL AND \"CompletedByUserId\" IS NULL AND \"CompletedAt\" IS NULL)");

                            t.HasCheckConstraint("CK_PhotographyRequests_Purpose", "\"Purpose\" IN ('GeneralDocumentation', 'PreMaintenance', 'DuringMaintenance', 'PostMaintenance')");

                            t.HasCheckConstraint("CK_PhotographyRequests_Status", "\"Status\" IN ('Pending', 'Completed', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.Photography.PhotographySet", b =>
                {
                    b.Property<Guid>("PhotographySetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uuid");

                    b.Property<int>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PhotographerUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateOnly>("PhotographyDate")
                        .HasColumnType("date");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("PhotographySetId");

                    b.HasIndex("ArtifactId");

                    b.ToTable("PhotographySets", "museum", t =>
                        {
                            t.HasCheckConstraint("CK_PhotographySets_Purpose", "\"Purpose\" IN ('GeneralDocumentation', 'PreMaintenance', 'DuringMaintenance', 'PostMaintenance')");
                        });
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.Photography.PhotographyUploadFileOutcome", b =>
                {
                    b.Property<Guid>("PhotographyUploadFileOutcomeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArtifactImageId")
                        .HasColumnType("uuid");

                    b.Property<int>("ClientFileOrdinal")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DerivativeObjectKeys")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("FinalizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InputFingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("OriginalFilename")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("OriginalObjectKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("PhotographyUploadOperationId")
                        .HasColumnType("uuid");

                    b.Property<string>("StaffFacingMessage")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("PhotographyUploadFileOutcomeId");

                    b.HasIndex("ArtifactImageId");

                    b.HasIndex("OriginalObjectKey")
                        .IsUnique();

                    b.HasIndex("PhotographyUploadOperationId", "ClientFileOrdinal")
                        .IsUnique();

                    b.ToTable("PhotographyUploadFileOutcomes", "museum", t =>
                        {
                            t.HasCheckConstraint("CK_PhotographyUploadFileOutcomes_ClientFileOrdinal", "\"ClientFileOrdinal\" >= 0");

                            t.HasCheckConstraint("CK_PhotographyUploadFileOutcomes_Status", "\"Status\" IN ('Succeeded', 'Rejected', 'Failed', 'CleanupPending', 'RecoveryNeeded')");
                        });
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.Photography.PhotographyUploadOperation", b =>
                {
                    b.Property<Guid>("PhotographyUploadOperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorUserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OperationKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("PhotographySetId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("PhotographyUploadOperationId");

                    b.HasIndex("ArtifactId");

                    b.HasIndex("PhotographySetId", "ArtifactId");

                    b.HasIndex("ActorUserId", "OperationKind", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("PhotographyUploadOperations", "museum", t =>
                        {
                            t.HasCheckConstraint("CK_PhotographyUploadOperations_OperationKind", "\"OperationKind\" IN ('CreateSetUpload', 'AppendToSetUpload')");

                            t.HasCheckConstraint("CK_PhotographyUploadOperations_Status", "\"Status\" IN ('InProgress', 'Completed', 'CompletedWithFailures', 'Failed', 'RecoveryNeeded')");
                        });
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.Photography.StorageOperationRecovery", b =>
                {
                    b.Property<Guid>("StorageOperationRecoveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArtifactImageId")
                        .HasColumnType("uuid");

                    b.Property<int>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureSummary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("LastAttemptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ObjectKeys")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("StorageOperationRecoveryId");

                    b.HasIndex("ArtifactId");

                    b.HasIndex("ArtifactImageId");

                    b.ToTable("StorageOperationRecoveries", "museum", t =>
                        {
                            t.HasCheckConstraint("CK_StorageOperationRecoveries_OperationType", "\"OperationType\" IN ('UploadCleanup', 'DeleteCleanup', 'DerivativeCleanup', 'MissingObject', 'DerivativeGeneration')");

                            t.HasCheckConstraint("CK_StorageOperationRecoveries_Status", "\"Status\" IN ('Pending', 'Retrying', 'Resolved', 'FailedNeedsAttention')");
                        });
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.StorehouseOperations.DocumentedCorrection", b =>
                {
                    b.Property<Guid>("CorrectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CorrectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CorrectedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("CorrectionType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("NewValueSummary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("PreviousValueSummary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("CorrectionId");

                    b.HasIndex("ArtifactId");

                    b.ToTable("DocumentedCorrections", "museum");
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.StorehouseOperations.Location", b =>
                {
                    b.Property<Guid>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("NameArabic")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ParentLocationId")
                        .HasColumnType("uuid");

                    b.HasKey("LocationId");

                    b.HasIndex("ParentLocationId");

                    b.HasIndex("NameArabic", "LocationType")
                        .IsUnique();

                    b.ToTable("Locations", "museum");
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.StorehouseOperations.MovementRecord", b =>
                {
                    b.Property<Guid>("MovementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MovementGroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Purpose")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("RecipientName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("RecipientType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RecordedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ReturnLocationId")
                        .HasColumnType("uuid");

                    b.HasKey("MovementId");

                    b.HasIndex("ArtifactId");

                    b.HasIndex("MovementGroupId");

                    b.HasIndex("ReturnLocationId");

                    b.ToTable("MovementRecords", "museum");
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.StorehouseOperations.ReconciliationResult", b =>
                {
                    b.Property<Guid>("ReconciliationResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArtifactId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ExpectedLocationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("IssueDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("ObservedLocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ObservedMuseumNumber")
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.Property<Guid>("ReconciliationSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResultType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("ReconciliationResultId");

                    b.HasIndex("ArtifactId");

                    b.HasIndex("ExpectedLocationId");

                    b.HasIndex("ObservedLocationId");

                    b.HasIndex("ReconciliationSessionId");

                    b.ToTable("ReconciliationResults", "museum");
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.StorehouseOperations.ReconciliationSession", b =>
                {
                    b.Property<Guid>("ReconciliationSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CompletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StartedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("ReconciliationSessionId");

                    b.HasIndex("LocationId");

                    b.ToTable("ReconciliationSessions", "museum");
                });

            modelBuilder.Entity("MuseumSystem.Infrastructure.Identity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", "museum");
                });

            modelBuilder.Entity("MuseumSystem.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", "museum");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("MuseumSystem.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("MuseumSystem.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("MuseumSystem.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("MuseumSystem.Infrastructure.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MuseumSystem.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("MuseumSystem.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.ArtifactRegistry.Artifact", b =>
                {
                    b.HasOne("MuseumSystem.Domain.Modules.ArtifactRegistry.ArtifactCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MuseumSystem.Domain.Modules.StorehouseOperations.Location", "CurrentLocation")
                        .WithMany()
                        .HasForeignKey("CurrentLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MuseumSystem.Domain.Modules.StorehouseOperations.Location", "LastKnownStorageLocation")
                        .WithMany()
                        .HasForeignKey("LastKnownStorageLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("CurrentLocation");

                    b.Navigation("LastKnownStorageLocation");
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.Documentation.DocumentationRecord", b =>
                {
                    b.HasOne("MuseumSystem.Domain.Modules.ArtifactRegistry.Artifact", null)
                        .WithMany()
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MuseumSystem.Domain.Modules.Documentation.DocumentationTemplateVersion", "DocumentationTemplateVersion")
                        .WithMany()
                        .HasForeignKey("DocumentationTemplateVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DocumentationTemplateVersion");
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.Documentation.DocumentationRevision", b =>
                {
                    b.HasOne("MuseumSystem.Domain.Modules.Documentation.DocumentationRecord", null)
                        .WithMany("Revisions")
                        .HasForeignKey("DocumentationRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MuseumSystem.Domain.Modules.Documentation.DocumentationTemplateVersion", null)
                        .WithMany()
                        .HasForeignKey("TemplateVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.Documentation.DocumentationTemplate", b =>
                {
                    b.HasOne("MuseumSystem.Domain.Modules.ArtifactRegistry.ArtifactCategory", null)
                        .WithMany()
                        .HasForeignKey("ArtifactCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.Documentation.DocumentationTemplateField", b =>
                {
                    b.HasOne("MuseumSystem.Domain.Modules.Documentation.DocumentationTemplateVersion", null)
                        .WithMany("Fields")
                        .HasForeignKey("DocumentationTemplateVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.Documentation.DocumentationTemplateFieldOption", b =>
                {
                    b.HasOne("MuseumSystem.Domain.Modules.Documentation.DocumentationTemplateField", null)
                        .WithMany("Options")
                        .HasForeignKey("DocumentationTemplateFieldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.Documentation.DocumentationTemplateVersion", b =>
                {
                    b.HasOne("MuseumSystem.Domain.Modules.Documentation.DocumentationTemplate", null)
                        .WithMany("Versions")
                        .HasForeignKey("DocumentationTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.Import.ImportRow", b =>
                {
                    b.HasOne("MuseumSystem.Domain.Modules.Import.ImportBatch", "ImportBatch")
                        .WithMany("Rows")
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ImportBatch");
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.Photography.ArtifactImage", b =>
                {
                    b.HasOne("MuseumSystem.Domain.Modules.ArtifactRegistry.Artifact", null)
                        .WithMany()
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MuseumSystem.Domain.Modules.Photography.PhotographySet", null)
                        .WithMany()
                        .HasForeignKey("PhotographySetId", "ArtifactId")
                        .HasPrincipalKey("PhotographySetId", "ArtifactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.Photography.ArtifactImageDerivative", b =>
                {
                    b.HasOne("MuseumSystem.Domain.Modules.Photography.ArtifactImage", null)
                        .WithMany("Derivatives")
                        .HasForeignKey("ArtifactImageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.Photography.ArtifactPhotographyState", b =>
                {
                    b.HasOne("MuseumSystem.Domain.Modules.ArtifactRegistry.Artifact", null)
                        .WithOne()
                        .HasForeignKey("MuseumSystem.Domain.Modules.Photography.ArtifactPhotographyState", "ArtifactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MuseumSystem.Domain.Modules.Photography.ArtifactImage", null)
                        .WithMany()
                        .HasForeignKey("PrimaryImageId", "ArtifactId")
                        .HasPrincipalKey("ArtifactImageId", "ArtifactId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.Photography.PhotographyRequest", b =>
                {
                    b.HasOne("MuseumSystem.Domain.Modules.ArtifactRegistry.Artifact", null)
                        .WithMany()
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MuseumSystem.Domain.Modules.Photography.PhotographySet", null)
                        .WithMany()
                        .HasForeignKey("FulfillingPhotographySetId", "ArtifactId", "Purpose")
                        .HasPrincipalKey("PhotographySetId", "ArtifactId", "Purpose")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.Photography.PhotographySet", b =>
                {
                    b.HasOne("MuseumSystem.Domain.Modules.ArtifactRegistry.Artifact", null)
                        .WithMany()
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.Photography.PhotographyUploadFileOutcome", b =>
                {
                    b.HasOne("MuseumSystem.Domain.Modules.Photography.ArtifactImage", null)
                        .WithMany()
                        .HasForeignKey("ArtifactImageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MuseumSystem.Domain.Modules.Photography.PhotographyUploadOperation", null)
                        .WithMany("FileOutcomes")
                        .HasForeignKey("PhotographyUploadOperationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.Photography.PhotographyUploadOperation", b =>
                {
                    b.HasOne("MuseumSystem.Domain.Modules.ArtifactRegistry.Artifact", null)
                        .WithMany()
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MuseumSystem.Domain.Modules.Photography.PhotographySet", null)
                        .WithMany()
                        .HasForeignKey("PhotographySetId", "ArtifactId")
                        .HasPrincipalKey("PhotographySetId", "ArtifactId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.Photography.StorageOperationRecovery", b =>
                {
                    b.HasOne("MuseumSystem.Domain.Modules.ArtifactRegistry.Artifact", null)
                        .WithMany()
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MuseumSystem.Domain.Modules.Photography.ArtifactImage", null)
                        .WithMany()
                        .HasForeignKey("ArtifactImageId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.StorehouseOperations.DocumentedCorrection", b =>
                {
                    b.HasOne("MuseumSystem.Domain.Modules.ArtifactRegistry.Artifact", "Artifact")
                        .WithMany()
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Artifact");
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.StorehouseOperations.Location", b =>
                {
                    b.HasOne("MuseumSystem.Domain.Modules.StorehouseOperations.Location", "ParentLocation")
                        .WithMany()
                        .HasForeignKey("ParentLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentLocation");
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.StorehouseOperations.MovementRecord", b =>
                {
                    b.HasOne("MuseumSystem.Domain.Modules.ArtifactRegistry.Artifact", "Artifact")
                        .WithMany()
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MuseumSystem.Domain.Modules.StorehouseOperations.Location", "ReturnLocation")
                        .WithMany()
                        .HasForeignKey("ReturnLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Artifact");

                    b.Navigation("ReturnLocation");
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.StorehouseOperations.ReconciliationResult", b =>
                {
                    b.HasOne("MuseumSystem.Domain.Modules.ArtifactRegistry.Artifact", "Artifact")
                        .WithMany()
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MuseumSystem.Domain.Modules.StorehouseOperations.Location", "ExpectedLocation")
                        .WithMany()
                        .HasForeignKey("ExpectedLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MuseumSystem.Domain.Modules.StorehouseOperations.Location", "ObservedLocation")
                        .WithMany()
                        .HasForeignKey("ObservedLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MuseumSystem.Domain.Modules.StorehouseOperations.ReconciliationSession", "ReconciliationSession")
                        .WithMany("Results")
                        .HasForeignKey("ReconciliationSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Artifact");

                    b.Navigation("ExpectedLocation");

                    b.Navigation("ObservedLocation");

                    b.Navigation("ReconciliationSession");
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.StorehouseOperations.ReconciliationSession", b =>
                {
                    b.HasOne("MuseumSystem.Domain.Modules.StorehouseOperations.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.Documentation.DocumentationRecord", b =>
                {
                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.Documentation.DocumentationTemplate", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.Documentation.DocumentationTemplateField", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.Documentation.DocumentationTemplateVersion", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.Import.ImportBatch", b =>
                {
                    b.Navigation("Rows");
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.Photography.ArtifactImage", b =>
                {
                    b.Navigation("Derivatives");
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.Photography.PhotographyUploadOperation", b =>
                {
                    b.Navigation("FileOutcomes");
                });

            modelBuilder.Entity("MuseumSystem.Domain.Modules.StorehouseOperations.ReconciliationSession", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
